steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mishpatly'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mishpatly'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mishpatly'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mishpatly'
      - '--region'
      - 'me-west1'
      - '--platform'
      - 'managed'

images:
  - 'gcr.io/$PROJECT_ID/mishpatly'

options:
  logging: CLOUD_LOGGING_ONLY
